name: Deploy

on:
  push:
    branches:
      - main



env:
  BOT_IMAGE: ${{ secrets.DOCKER_USERNAME }}/bot-otaku:${{ github.sha }}

jobs:
  build-push-bot:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://cloud.yandex.com/en-ru/
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.BOT_IMAGE }}

  deploy:
    name: Deployming to yandex cloud
    runs-on: ubuntu-latest
    needs: build-push-bot
    environment: 
      name: production
      url: https://cloud.yandex.com/en-ru/
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Deploy container
        run: echo "hello"


